name: email 

on:
  schedule:
    - cron: '00 9 * * 1,4'
  workflow_dispatch:
    
env:
    REPORT_DIR: /data/watchtower/amos/container-results/amos-ui

jobs:
    send-email:
        runs-on: "th878"
        steps:
        - name: Email latest report
          uses: USEPA/email-report@main
          with:
                report_path: ${{ env.REPORT_DIR }}/amos-ui-report.html
                recipients: ${{ vars.REPORT_RECIPIENTS }}
                sender: ${{ vars.REPORT_SENDER }}
                subject: "ccddashboard-ui  Scan Report"
                body: |
                    Hello,

                    Please find attached the ccddashboard-ui  scan report.

                    Best regards.