name: Generate SBOM
on:
  push:
    branches: [ "test1" ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Generate and Upload SBOM
      uses: USEPA/ccte-sbom-generator-vue@main
      with:
        node_version: '20'
        server_hostname: 'ccte-api-dependency-track.epa.gov'
        api_key: ${{ secrets.SECRET_OWASP_DT_KEY }}
        project_name: 'chemtrack-ui'
        project_version: ${{ github.ref_name }}
